Attach hex_scale and reward_unit to poc witness and receipts
helium/proto pull request #280
Opened 2023-02-08 17:25 UTC by vihu

2023-02-08 19:39 UTC, madninja requested changes

2023-02-08 19:39 UTC, madninja commented on src/blockchain_poc_core_v1.proto
> +  optional uint32 reward_unit = 11;
you can't do these.. not supported by all but the latest protoc compilers. The "default value" is how optional is done for proto3 primitives

2023-02-08 23:13 UTC, vihu commented on src/blockchain_poc_core_v1.proto
> +  optional uint32 reward_unit = 11;
Uh, alright then

2023-02-10 10:43 UTC, andymck approved these changes

2023-02-22 19:50 UTC, madninja approved these changes

2023-02-22 19:50 UTC, merged